### ISSUE TITLE
[Bugfix] The Usage of Plot2D Function in RefocusedEcho2DAnalysis()

### ISSUE THREAD

**Issue by ehuang94** [JeschkeLab/autoDEER#78]
The arguments of plot2D in main.py (line 762) doesn't work and gives the error: list index is out of range.

main.py: 
`self.current_results['relax2D'].plot2D(axs=self.relax_ax[0],fig=fig)`

Relaxation.py:
`plot2D(self, contour=True,smooth=False, norm = 'Normal', axs=None, fig=None)`

**Comment by HKaras** [comment]
Please can you supply the full tracelog, it's hard to debug without. I haven't seen this issue before and had run the 4pDEER mode multiple times.

**Comment by ehuang94** [comment]
The error is confirmed from my end. I will close this request.
