### ISSUE TITLE
[Bugfix] Wrong Axis to Acquire Tau2 in 4pDEER in Relaxation

### ISSUE THREAD

**Issue by ehuang94** [JeschkeLab/autoDEER#79]
In RefocusedEcho2DAnalysi(), when selecting tau2 dimension from whole dataset, np.max is used. However, the axis is wrong. It should be 0 instead of 1.

The reason is if axis=1, the function will return the maximum value along tau2 dimension. In other words, the function first 'fix' the tau1 to return the maximum, and then move to the next tau1 to return the maximum, and so on. Eventually, it will returns tau1 values and tau1 axis, and the tau2 axis will be removed.

**Comment by HKaras** [comment]
The axis tau1=tau2 acts as a symetry point. It makes no difference if the axis is 0 or 1, the result is the same.

https://github.com/JeschkeLab/autoDEER/blob/84d8bb27b34ecec2d233d190d3a8c003ad813de9/autodeer/Relaxation.py#L539
